<?xml version="1.0"?>
<package format="3">
  <name>gru_predictor</name>
  <version>0.1.0</version>
  <description>ROS2 GRU hybrid trajectory predictor for LV-DOT dynamic boxes.</description>
  <maintainer email="devnull@example.com">skbt2</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>python3-yaml</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
