from pathlib import Path

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition, UnlessCondition
from launch.substitutions import LaunchConfiguration, PythonExpression
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue

def generate_launch_description() -> LaunchDescription:
    bringup_dir = Path(get_package_share_directory("lvdot_bringup"))
    default_config_path = str(bringup_dir / "config" / "detector_param.yaml")

    return LaunchDescription([
        DeclareLaunchArgument("use_gt_detections", default_value="false"),
        DeclareLaunchArgument("enable_yolo", default_value="false"),
        DeclareLaunchArgument("use_all_classes", default_value="false"),
        DeclareLaunchArgument("enable_color_fallback", default_value="false"),
        DeclareLaunchArgument("conf_threshold", default_value="0.25"),
        DeclareLaunchArgument("launch_relay", default_value="true"),
        DeclareLaunchArgument("launch_pose_stub", default_value="false"),
        DeclareLaunchArgument("pose_stub_orbit_enabled", default_value="false"),
        DeclareLaunchArgument("pose_stub_orbit_radius", default_value="0.4"),
        DeclareLaunchArgument("pose_stub_orbit_speed", default_value="0.3"),
        DeclareLaunchArgument("pose_mode", default_value="orbit"),
        DeclareLaunchArgument("mission_speed", default_value="1.5"),
        DeclareLaunchArgument("mission_altitude", default_value="1.2"),
        DeclareLaunchArgument("scenario_config", default_value=""),
        DeclareLaunchArgument("launch_yolo_node", default_value="true"),
        DeclareLaunchArgument("launch_evaluator", default_value="false"),
        DeclareLaunchArgument("launch_advanced_evaluator", default_value="false"),
        DeclareLaunchArgument("evaluator_csv_path", default_value="/tmp/lvdot_eval.csv"),
        DeclareLaunchArgument("evaluator_summary_path", default_value="/tmp/lvdot_eval_summary.json"),
        DeclareLaunchArgument("evaluator_matched_pairs_csv_path", default_value=""),
        DeclareLaunchArgument("evaluator_tracking_pairs_csv_path", default_value=""),
        DeclareLaunchArgument("evaluator_match_threshold_m", default_value="1.5"),
        DeclareLaunchArgument("evaluator_include_static_obstacles", default_value="false"),
        DeclareLaunchArgument("evaluator_gt_obstacle_topic", default_value="/pedestrian_sim/agent_markers"),
        DeclareLaunchArgument("evaluator_gt_obstacle_namespace", default_value="pedestrian_obstacles"),
        DeclareLaunchArgument("evaluator_det_topic", default_value="/onboard_detector/dynamic_bboxes"),
        DeclareLaunchArgument("evaluator_pred_topic", default_value="/gru_predictor/predicted_positions"),
        DeclareLaunchArgument("evaluator_det_marker_type", default_value="5"),
        DeclareLaunchArgument("evaluator_det_namespace", default_value="dynamic"),
        DeclareLaunchArgument("evaluator_tracking_det_topic", default_value=""),
        DeclareLaunchArgument("evaluator_tracking_det_marker_type", default_value="-1"),
        DeclareLaunchArgument("evaluator_tracking_det_namespace", default_value=""),
        DeclareLaunchArgument("evaluator_eval_duration_sec", default_value="60.0"),
        DeclareLaunchArgument("evaluator_warmup_sec", default_value="15.0"),
        DeclareLaunchArgument("evaluator_center_match_threshold_m", default_value="1.0"),
        DeclareLaunchArgument("evaluator_gt_bbox_width_m", default_value="0.36"),
        DeclareLaunchArgument("evaluator_gt_bbox_depth_m", default_value="0.36"),
        DeclareLaunchArgument("evaluator_gt_bbox_height_m", default_value="1.70"),
        DeclareLaunchArgument("evaluator_gt_bbox_center_y_offset_m", default_value="-0.03"),
        DeclareLaunchArgument("evaluator_gt_bbox_center_z_offset_m", default_value="0.88"),
        DeclareLaunchArgument("imgsz", default_value="352"),
        DeclareLaunchArgument("max_det", default_value="10"),
        DeclareLaunchArgument("inference_hz", default_value="10.0"),
        DeclareLaunchArgument("frame_stride", default_value="1"),
        DeclareLaunchArgument(
            "yolo_weight_path",
            default_value=str(next((__wsp for __wsp in Path(__file__).resolve().parents if (__wsp / "models" / "qcgaf").is_dir()), Path(__file__).resolve().parents[3]) / "models" / "yolo" / "yolo11n.engine"),
        ),
        DeclareLaunchArgument("enable_stage_timers", default_value="true"),
        DeclareLaunchArgument("enable_vis_stage", default_value="true"),
        DeclareLaunchArgument("executor_threads", default_value="4"),
        DeclareLaunchArgument("rviz", default_value="false"),
        DeclareLaunchArgument("detector_config", default_value=default_config_path),
        DeclareLaunchArgument("use_sim_time", default_value="true"),
        DeclareLaunchArgument("depth_image_topic", default_value="/rgbd_camera/depth_image"),
        DeclareLaunchArgument("color_image_topic", default_value="/rgbd_camera/image"),
        DeclareLaunchArgument("lidar_pointcloud_topic", default_value="/livox/lidar/pointcloud"),
        DeclareLaunchArgument("pose_topic", default_value="/mavros/local_position/pose"),
        DeclareLaunchArgument("odom_topic", default_value="/mavros/local_position/odom"),
        DeclareLaunchArgument("yolo_detection_topic", default_value="/yolo_detector/detected_bounding_boxes"),
        DeclareLaunchArgument("fusion_mode", default_value="dual"),
        DeclareLaunchArgument("depth_branch_offset_sec", default_value="0.20"),
        DeclareLaunchArgument("depth_branch_history_size", default_value="32"),
        DeclareLaunchArgument("max_depth_lidar_skew_sec", default_value="0.18"),
        DeclareLaunchArgument("u_map_threshold_point", default_value="1"),
        DeclareLaunchArgument("u_map_threshold_line", default_value="1"),
        DeclareLaunchArgument("u_map_min_length_line", default_value="1"),
        Node(
            package="lvdot_ros2_adapter",
            executable="image_pointcloud_relay",
            output="screen",
            parameters=[{"use_sim_time": LaunchConfiguration("use_sim_time")}],
            condition=IfCondition(LaunchConfiguration("launch_relay")),
        ),
        Node(
            package="lvdot_ros2_adapter",
            executable="pose_stub",
            output="screen",
            parameters=[{
                "use_sim_time": LaunchConfiguration("use_sim_time"),
                "scenario_config": LaunchConfiguration("scenario_config"),
                "orbit_enabled": LaunchConfiguration("pose_stub_orbit_enabled"),
                "orbit_radius": LaunchConfiguration("pose_stub_orbit_radius"),
                "orbit_speed_rad_s": LaunchConfiguration("pose_stub_orbit_speed"),
            }],
            condition=IfCondition(PythonExpression([
                "'", LaunchConfiguration("launch_pose_stub"), "' == 'true' and '",
                LaunchConfiguration("pose_mode"), "' != 'mission'"])),
        ),
        Node(
            package="lvdot_ros2_adapter",
            executable="uav_waypoint_mission",
            output="screen",
            parameters=[{
                "use_sim_time": LaunchConfiguration("use_sim_time"),
                "scenario_config": LaunchConfiguration("scenario_config"),
                "speed": LaunchConfiguration("mission_speed"),
                "altitude": LaunchConfiguration("mission_altitude"),
            }],
            condition=IfCondition(PythonExpression([
                "'", LaunchConfiguration("launch_pose_stub"), "' == 'true' and '",
                LaunchConfiguration("pose_mode"), "' == 'mission'"])),
        ),
        Node(
            package="lvdot_ros2_adapter",
            executable="lvdot_yolo_node",
            output="screen",
            parameters=[{
                "image_topic": LaunchConfiguration("color_image_topic"),
                "enable_yolo": LaunchConfiguration("enable_yolo"),
                "use_all_classes": LaunchConfiguration("use_all_classes"),
                "enable_color_fallback": LaunchConfiguration("enable_color_fallback"),
                "conf_threshold": LaunchConfiguration("conf_threshold"),
                "imgsz": LaunchConfiguration("imgsz"),
                "max_det": LaunchConfiguration("max_det"),
                "inference_hz": LaunchConfiguration("inference_hz"),
                "frame_stride": LaunchConfiguration("frame_stride"),
                "weight_path": LaunchConfiguration("yolo_weight_path"),
                "use_sim_time": LaunchConfiguration("use_sim_time"),
            }],
            additional_env={"CUDA_VISIBLE_DEVICES": "1"},
            condition=IfCondition(LaunchConfiguration("launch_yolo_node")),
        ),
        Node(
            package="lvdot_ros2",
            executable="lvdot_detector_main",
            name="lvdot_detector_node",
            output="screen",
            parameters=[
                LaunchConfiguration("detector_config"),
                {
                    "enable_stage_timers": LaunchConfiguration("enable_stage_timers"),
                    "enable_vis_stage": LaunchConfiguration("enable_vis_stage"),
                    "executor_threads": LaunchConfiguration("executor_threads"),
                    "depth_image_topic": LaunchConfiguration("depth_image_topic"),
                    "color_image_topic": LaunchConfiguration("color_image_topic"),
                    "lidar_pointcloud_topic": LaunchConfiguration("lidar_pointcloud_topic"),
                    "pose_topic": LaunchConfiguration("pose_topic"),
                    "odom_topic": LaunchConfiguration("odom_topic"),
                    "yolo_detection_topic": LaunchConfiguration("yolo_detection_topic"),
                    "fusion_mode": LaunchConfiguration("fusion_mode"),
                    "use_sim_time": LaunchConfiguration("use_sim_time"),
                    "depth_branch_offset_sec": LaunchConfiguration("depth_branch_offset_sec"),
                    "depth_branch_history_size": ParameterValue(
                        LaunchConfiguration("depth_branch_history_size"), value_type=int),
                    "max_depth_lidar_skew_sec": LaunchConfiguration("max_depth_lidar_skew_sec"),
                    "u_map_threshold_point": ParameterValue(LaunchConfiguration("u_map_threshold_point"), value_type=int),
                    "u_map_threshold_line": ParameterValue(LaunchConfiguration("u_map_threshold_line"), value_type=int),
                    "u_map_min_length_line": ParameterValue(LaunchConfiguration("u_map_min_length_line"), value_type=int),
                },
            ],
        ),
        Node(
            package="rviz2",
            executable="rviz2",
            name="lvdot_detector_rviz",
            output="screen",
            arguments=["-d", str(bringup_dir / "rviz" / "lvdot_detector.rviz")],
            parameters=[{"use_sim_time": LaunchConfiguration("use_sim_time")}],
            condition=IfCondition(LaunchConfiguration("rviz")),
        ),
        Node(
            package="lvdot_ros2_adapter",
            executable="detection_evaluator",
            name="detection_evaluator",
            output="screen",
            parameters=[{
                "gt_topic": "/pedestrian_sim/agent_states",
                "det_topic": LaunchConfiguration("evaluator_det_topic"),
                "match_threshold_m": LaunchConfiguration("evaluator_match_threshold_m"),
                "csv_path": LaunchConfiguration("evaluator_csv_path"),
                "log_every_sec": 5.0,
                "det_marker_type": ParameterValue(LaunchConfiguration("evaluator_det_marker_type"), value_type=int),
                "det_namespace": LaunchConfiguration("evaluator_det_namespace"),
                "use_sim_time": LaunchConfiguration("use_sim_time"),
            }],
            condition=IfCondition(LaunchConfiguration("launch_evaluator")),
        ),
        Node(
            package="lvdot_ros2_adapter",
            executable="advanced_evaluator",
            name="advanced_evaluator",
            output="screen",
            parameters=[{
                "gt_topic": "/pedestrian_sim/agent_states",
                "gt_obstacle_topic": LaunchConfiguration("evaluator_gt_obstacle_topic"),
                "gt_obstacle_namespace": LaunchConfiguration("evaluator_gt_obstacle_namespace"),
                "include_static_obstacles": LaunchConfiguration("evaluator_include_static_obstacles"),
                "det_topic": LaunchConfiguration("evaluator_det_topic"),
                "tracking_det_topic": LaunchConfiguration("evaluator_tracking_det_topic"),
                "pred_topic": LaunchConfiguration("evaluator_pred_topic"),
                "csv_path": LaunchConfiguration("evaluator_csv_path"),
                "summary_path": LaunchConfiguration("evaluator_summary_path"),
                "matched_pairs_csv_path": LaunchConfiguration("evaluator_matched_pairs_csv_path"),
                "tracking_pairs_csv_path": LaunchConfiguration("evaluator_tracking_pairs_csv_path"),
                "det_marker_type": ParameterValue(LaunchConfiguration("evaluator_det_marker_type"), value_type=int),
                "det_namespace": LaunchConfiguration("evaluator_det_namespace"),
                "tracking_det_marker_type": ParameterValue(LaunchConfiguration("evaluator_tracking_det_marker_type"), value_type=int),
                "tracking_det_namespace": LaunchConfiguration("evaluator_tracking_det_namespace"),
                "eval_duration_sec": LaunchConfiguration("evaluator_eval_duration_sec"),
                "warmup_sec": LaunchConfiguration("evaluator_warmup_sec"),
                "center_match_threshold_m": LaunchConfiguration("evaluator_center_match_threshold_m"),
                "gt_bbox_width_m": LaunchConfiguration("evaluator_gt_bbox_width_m"),
                "gt_bbox_depth_m": LaunchConfiguration("evaluator_gt_bbox_depth_m"),
                "gt_bbox_height_m": LaunchConfiguration("evaluator_gt_bbox_height_m"),
                "gt_bbox_center_y_offset_m": LaunchConfiguration("evaluator_gt_bbox_center_y_offset_m"),
                "gt_bbox_center_z_offset_m": LaunchConfiguration("evaluator_gt_bbox_center_z_offset_m"),
                "use_sim_time": LaunchConfiguration("use_sim_time"),
            }],
            condition=IfCondition(LaunchConfiguration("launch_advanced_evaluator")),
        ),
    ])
