from pathlib import Path

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.conditions import IfCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, PythonExpression


def generate_launch_description() -> LaunchDescription:
    detector_launch = Path(get_package_share_directory("lvdot_bringup")) / "launch" / "run_detector_with_adapter.launch.py"
    depth_eval_share = Path(get_package_share_directory("depth_eval_bringup"))
    scene_launch = depth_eval_share / "launch" / "uav_pedestrian_clean_2agents.launch.py"
    realistic_sensors_launch = Path(get_package_share_directory("lvdot_realistic_sensors")) / "launch" / "realistic_sensors.launch.py"
    default_scenario_config = str(
        Path(get_package_share_directory("lvdot_bringup")) / "config" / "clean_scenarios" / "pedestrian_clean_02agents.yaml")

    use_realistic = LaunchConfiguration("use_realistic_sensors")

    def pick(realistic_topic: str, raw_topic: str) -> PythonExpression:
        return PythonExpression([
            "'", realistic_topic, "' if '", use_realistic, "' == 'true' else '", raw_topic, "'",
        ])

    return LaunchDescription([
        DeclareLaunchArgument("use_realistic_sensors", default_value="true"),
        DeclareLaunchArgument("gazebo_gui", default_value="false"),
        DeclareLaunchArgument("rviz", default_value="false"),
        DeclareLaunchArgument("detector_rviz", default_value="false"),
        DeclareLaunchArgument("detector_config", default_value=""),
        DeclareLaunchArgument("scenario_config", default_value=default_scenario_config),
        DeclareLaunchArgument("enable_uav_controller", default_value="false"),
        DeclareLaunchArgument("enable_stage_timers", default_value="true"),
        DeclareLaunchArgument("enable_vis_stage", default_value="true"),
        DeclareLaunchArgument("executor_threads", default_value="4"),
        DeclareLaunchArgument("enable_yolo", default_value="false"),
        DeclareLaunchArgument("launch_yolo_node", default_value="false"),
        DeclareLaunchArgument("use_all_classes", default_value="false"),
        DeclareLaunchArgument("enable_color_fallback", default_value="false"),
        DeclareLaunchArgument("conf_threshold", default_value="0.25"),
        DeclareLaunchArgument("imgsz", default_value="352"),
        DeclareLaunchArgument("max_det", default_value="10"),
        DeclareLaunchArgument("inference_hz", default_value="30.0"),
        DeclareLaunchArgument("frame_stride", default_value="1"),
        DeclareLaunchArgument(
            "yolo_weight_path",
            default_value=str(next((__wsp for __wsp in Path(__file__).resolve().parents if (__wsp / "models" / "qcgaf").is_dir()), Path(__file__).resolve().parents[3]) / "models" / "yolo" / "yolo11n.engine"),
        ),
        DeclareLaunchArgument("launch_pose_stub", default_value="true"),
        DeclareLaunchArgument("pose_stub_orbit_enabled", default_value="false"),
        DeclareLaunchArgument("pose_stub_orbit_radius", default_value="0.4"),
        DeclareLaunchArgument("pose_stub_orbit_speed", default_value="0.3"),
        DeclareLaunchArgument("pose_mode", default_value="orbit"),
        DeclareLaunchArgument("mission_speed", default_value="1.5"),
        DeclareLaunchArgument("mission_altitude", default_value="1.2"),
        DeclareLaunchArgument("launch_evaluator", default_value="false"),
        DeclareLaunchArgument("launch_advanced_evaluator", default_value="false"),
        DeclareLaunchArgument("evaluator_csv_path", default_value="/tmp/lvdot_eval.csv"),
        DeclareLaunchArgument("evaluator_summary_path", default_value="/tmp/lvdot_eval_summary.json"),
        DeclareLaunchArgument("evaluator_matched_pairs_csv_path", default_value=""),
        DeclareLaunchArgument("evaluator_tracking_pairs_csv_path", default_value=""),
        DeclareLaunchArgument("evaluator_match_threshold_m", default_value="1.5"),
        DeclareLaunchArgument("evaluator_include_static_obstacles", default_value="false"),
        DeclareLaunchArgument("evaluator_gt_obstacle_topic", default_value="/pedestrian_sim/agent_markers"),
        DeclareLaunchArgument("evaluator_gt_obstacle_namespace", default_value="pedestrian_obstacles"),
        DeclareLaunchArgument("evaluator_det_topic", default_value="/onboard_detector/dynamic_bboxes"),
        DeclareLaunchArgument("evaluator_pred_topic", default_value="/gru_predictor/predicted_positions"),
        DeclareLaunchArgument("evaluator_det_marker_type", default_value="5"),
        DeclareLaunchArgument("evaluator_det_namespace", default_value="dynamic"),
        DeclareLaunchArgument("evaluator_tracking_det_topic", default_value=""),
        DeclareLaunchArgument("evaluator_tracking_det_marker_type", default_value="-1"),
        DeclareLaunchArgument("evaluator_tracking_det_namespace", default_value=""),
        DeclareLaunchArgument("evaluator_eval_duration_sec", default_value="60.0"),
        DeclareLaunchArgument("evaluator_warmup_sec", default_value="15.0"),
        DeclareLaunchArgument("evaluator_center_match_threshold_m", default_value="1.0"),
        DeclareLaunchArgument("evaluator_gt_bbox_width_m", default_value="0.36"),
        DeclareLaunchArgument("evaluator_gt_bbox_depth_m", default_value="0.36"),
        DeclareLaunchArgument("evaluator_gt_bbox_height_m", default_value="1.70"),
        DeclareLaunchArgument("evaluator_gt_bbox_center_y_offset_m", default_value="-0.03"),
        DeclareLaunchArgument("evaluator_gt_bbox_center_z_offset_m", default_value="0.88"),
        DeclareLaunchArgument("u_map_threshold_point", default_value="1"),
        DeclareLaunchArgument("u_map_threshold_line", default_value="1"),
        DeclareLaunchArgument("u_map_min_length_line", default_value="1"),
        DeclareLaunchArgument("depth_branch_offset_sec", default_value="0.20"),
        DeclareLaunchArgument("depth_branch_history_size", default_value="32"),
        DeclareLaunchArgument("max_depth_lidar_skew_sec", default_value="0.80"),
        DeclareLaunchArgument("use_sim_time", default_value="true"),
        DeclareLaunchArgument("mid360_points_per_frame", default_value="28000"),
        DeclareLaunchArgument("mid360_range_noise_per_m", default_value="0.0008"),
        DeclareLaunchArgument("d435_depth_noise_coef", default_value="0.0000"),
        DeclareLaunchArgument("d435_dropout_prob", default_value="0.00"),
        DeclareLaunchArgument("d435_quantize_mm", default_value="true"),
        DeclareLaunchArgument(
            "color_image_topic",
            default_value=pick("/d435i/color/image_raw", "/rgbd_camera/image"),
        ),
        DeclareLaunchArgument(
            "depth_image_topic",
            default_value=pick("/d435i/depth/image_rect_raw", "/rgbd_camera/depth_image"),
        ),
        DeclareLaunchArgument(
            "lidar_pointcloud_topic",
            default_value=pick("/mid360/pointcloud", "/uav_lidar/scan/points"),
        ),
        IncludeLaunchDescription(
            PythonLaunchDescriptionSource(str(scene_launch)),
            launch_arguments={
                "rviz": LaunchConfiguration("rviz"),
                "gazebo_gui": LaunchConfiguration("gazebo_gui"),
                "enable_uav_controller": LaunchConfiguration("enable_uav_controller"),
                "relay_lvdot_topics": "false",
                "scenario_config": LaunchConfiguration("scenario_config"),
            }.items(),
        ),
        IncludeLaunchDescription(
            PythonLaunchDescriptionSource(str(realistic_sensors_launch)),
            launch_arguments={
                "use_sim_time": LaunchConfiguration("use_sim_time"),
                "mid360_points_per_frame": LaunchConfiguration("mid360_points_per_frame"),
                "mid360_range_noise_per_m": LaunchConfiguration("mid360_range_noise_per_m"),
                "d435_depth_noise_coef": LaunchConfiguration("d435_depth_noise_coef"),
                "d435_dropout_prob": LaunchConfiguration("d435_dropout_prob"),
                "d435_quantize_mm": LaunchConfiguration("d435_quantize_mm"),
            }.items(),
            condition=IfCondition(use_realistic),
        ),
        IncludeLaunchDescription(
            PythonLaunchDescriptionSource(str(detector_launch)),
            launch_arguments={
                "launch_relay": "false",
                "launch_pose_stub": LaunchConfiguration("launch_pose_stub"),
                "pose_stub_orbit_enabled": LaunchConfiguration("pose_stub_orbit_enabled"),
                "pose_stub_orbit_radius": LaunchConfiguration("pose_stub_orbit_radius"),
                "pose_stub_orbit_speed": LaunchConfiguration("pose_stub_orbit_speed"),
                "pose_mode": LaunchConfiguration("pose_mode"),
                "mission_speed": LaunchConfiguration("mission_speed"),
                "mission_altitude": LaunchConfiguration("mission_altitude"),
                "launch_evaluator": LaunchConfiguration("launch_evaluator"),
                "launch_advanced_evaluator": LaunchConfiguration("launch_advanced_evaluator"),
                "evaluator_csv_path": LaunchConfiguration("evaluator_csv_path"),
                "evaluator_summary_path": LaunchConfiguration("evaluator_summary_path"),
                "evaluator_matched_pairs_csv_path": LaunchConfiguration("evaluator_matched_pairs_csv_path"),
                "evaluator_tracking_pairs_csv_path": LaunchConfiguration("evaluator_tracking_pairs_csv_path"),
                "evaluator_match_threshold_m": LaunchConfiguration("evaluator_match_threshold_m"),
                "evaluator_include_static_obstacles": LaunchConfiguration("evaluator_include_static_obstacles"),
                "evaluator_gt_obstacle_topic": LaunchConfiguration("evaluator_gt_obstacle_topic"),
                "evaluator_gt_obstacle_namespace": LaunchConfiguration("evaluator_gt_obstacle_namespace"),
                "evaluator_det_topic": LaunchConfiguration("evaluator_det_topic"),
                "evaluator_pred_topic": LaunchConfiguration("evaluator_pred_topic"),
                "evaluator_det_marker_type": LaunchConfiguration("evaluator_det_marker_type"),
                "evaluator_det_namespace": LaunchConfiguration("evaluator_det_namespace"),
                "evaluator_tracking_det_topic": LaunchConfiguration("evaluator_tracking_det_topic"),
                "evaluator_tracking_det_marker_type": LaunchConfiguration("evaluator_tracking_det_marker_type"),
                "evaluator_tracking_det_namespace": LaunchConfiguration("evaluator_tracking_det_namespace"),
                "evaluator_eval_duration_sec": LaunchConfiguration("evaluator_eval_duration_sec"),
                "evaluator_warmup_sec": LaunchConfiguration("evaluator_warmup_sec"),
                "evaluator_center_match_threshold_m": LaunchConfiguration("evaluator_center_match_threshold_m"),
                "evaluator_gt_bbox_width_m": LaunchConfiguration("evaluator_gt_bbox_width_m"),
                "evaluator_gt_bbox_depth_m": LaunchConfiguration("evaluator_gt_bbox_depth_m"),
                "evaluator_gt_bbox_height_m": LaunchConfiguration("evaluator_gt_bbox_height_m"),
                "evaluator_gt_bbox_center_y_offset_m": LaunchConfiguration("evaluator_gt_bbox_center_y_offset_m"),
                "evaluator_gt_bbox_center_z_offset_m": LaunchConfiguration("evaluator_gt_bbox_center_z_offset_m"),
                "u_map_threshold_point": LaunchConfiguration("u_map_threshold_point"),
                "u_map_threshold_line": LaunchConfiguration("u_map_threshold_line"),
                "u_map_min_length_line": LaunchConfiguration("u_map_min_length_line"),
                "depth_branch_offset_sec": LaunchConfiguration("depth_branch_offset_sec"),
                "depth_branch_history_size": LaunchConfiguration("depth_branch_history_size"),
                "max_depth_lidar_skew_sec": LaunchConfiguration("max_depth_lidar_skew_sec"),
                "launch_yolo_node": LaunchConfiguration("launch_yolo_node"),
                "enable_yolo": LaunchConfiguration("enable_yolo"),
                "use_all_classes": LaunchConfiguration("use_all_classes"),
                "enable_color_fallback": LaunchConfiguration("enable_color_fallback"),
                "conf_threshold": LaunchConfiguration("conf_threshold"),
                "imgsz": LaunchConfiguration("imgsz"),
                "max_det": LaunchConfiguration("max_det"),
                "inference_hz": LaunchConfiguration("inference_hz"),
                "frame_stride": LaunchConfiguration("frame_stride"),
                "yolo_weight_path": LaunchConfiguration("yolo_weight_path"),
                "enable_stage_timers": LaunchConfiguration("enable_stage_timers"),
                "enable_vis_stage": LaunchConfiguration("enable_vis_stage"),
                "executor_threads": LaunchConfiguration("executor_threads"),
                "scenario_config": LaunchConfiguration("scenario_config"),
                "color_image_topic": LaunchConfiguration("color_image_topic"),
                "depth_image_topic": LaunchConfiguration("depth_image_topic"),
                "lidar_pointcloud_topic": LaunchConfiguration("lidar_pointcloud_topic"),
                "rviz": LaunchConfiguration("detector_rviz"),
                "detector_config": LaunchConfiguration("detector_config"),
                "use_sim_time": LaunchConfiguration("use_sim_time"),
            }.items(),
        ),
    ])
