data:
  min_track_length: 12
  nuscenes_root: /home/LV-DOT/data/nuscenes
  nuscenes_version: v1.0-mini
gru:
  hidden_dim: 64
  input_dim: 9
  num_layers: 1
  output_dim: 3
  seq_len: 10
hybrid:
  beta_s: 0.5
  c_max: 30
  error_window: 5
kalman:
  avg_frames: 2
  dt: 0.5
  eP: 0.25
  eQ_acc: 0.1
  eQ_pos: 0.01
  eQ_vel: 0.1
  eR_acc: 1.0
  eR_pos: 0.02
  eR_vel: 0.6
train:
  batch_size: 64
  epochs: 200
  learning_rate: 0.001
  patience: 20
