<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>lvdot_bringup</name>
  <version>0.0.0</version>
  <description>Bringup package for LV-DOT ROS2 migration.</description>
  <maintainer email="skbt2@todo.todo">skbt2</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>gru_predictor</exec_depend>
  <exec_depend>lvdot_interfaces</exec_depend>
  <exec_depend>lvdot_realistic_sensors</exec_depend>
  <exec_depend>lvdot_ros2</exec_depend>
  <exec_depend>qcgaf_fusion</exec_depend>
  <exec_depend>rclpy</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
